server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: serie-service
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    baseUrl: http://localhost:9411/
  #mongodb:
  #embedded:
  #version: 4.0.2
  data:
    mongodb:
      #authentication-database: admin
      username: usr-series-mongo
      password: pwd-series-mongo
      database: series-dev-mongo
      port: 27018

info:
  application:
    name: api-serie

eureka:
  healthcheck:
    enabled: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
